### ISSUE TITLE
How come training is so fast?

### ISSUE THREAD

**Issue by urialon** [eth-sri/debin#1]
Hi,
Very interesting paper, and thanks for making the code and the website available!

The "Training" section says that: "The processes take less than a minute and the trained models are produced in ./new_models."

1. How come training takes less than a minute? Doesn't it depend on the number of binaries in the binaries list?
I have used Nice2Predict before, and it may take much more time to train, depending on the training data size. 

2. Additionally, why do the instructions say "models" and not a single "model"? Isn't it training a single model for all the training binaries?

Thanks!

**Comment by LostBenjamin** [comment]
Thanks for your interest in the paper! Here are the answers:

1. By "less than a minute", we refer to the example command in the section, which takes only one training binary. Indeed, training time depends on training data size and machine resources.

2. There are two training commands so two types of models are trained, both for all training binaries. The first is invoked by `python3 py/train_variable.py` which trains models to distinguish variables from temporarily used registers and memory offsets. The second is invoked by `py/train_crf.py` which trains a CRF model with Nice2Predict.

**Comment by urialon** [comment]
Thanks!!
