### ISSUE TITLE
Evaluation deal with only one sample

### ISSUE THREAD

**Issue by mingfure** [eth-sri/debin#11]
Hi，
Thanks for your sharing~
What confuse me is, why does the `evaluate.py` only handle one binary at a time?

In your paper, you used 3000 binaries for each architecture (2700 for training, 300 for tests). 
Input to both variable classifier and structured predictions are `--bin_dir` and `--debug_dir`, but the input to `evaluate.py` is only 2 binaries with `--binary` and `--debug_info`. 
In my understanding, the evaluation result should be something like the average of all test set measures. 
So in order to do that, do I need to modify `evaluate.py` for multiple binaries? Or do I have any misunderstanding, please tell me~
Thanks!

**Comment by LostBenjamin** [comment]
Hi,

We only release scripts that perform prediction or evaluation on one binary. With those scripts, I think you can easily write your own scripts to handle multiple binaries, or use tools like `xargs` and GNU `parallel` to achieve parallelization.

Best,
Jingxuan

**Comment by mingfure** [comment]
I see~
Thank you!
