### ISSUE TITLE
List of supported ARM architectures

### ISSUE THREAD

**Issue by francozappa** [eth-sri/debin#12]
Hi,

Thanks for sharing the project.

Do you have a list of supported ARM architectures?

**Comment by LostBenjamin** [comment]
Hi,

Thanks for your interest in the project.

DEBIN uses [BAP](https://github.com/BinaryAnalysisPlatform/bap) as analysis engine. BAP does not support well for thumb instructions ([link](https://github.com/BinaryAnalysisPlatform/bap/issues/951)). Neither does DEBIN. In our experiments, we use ARM images in [this link](https://people.debian.org/~aurel32/qemu/armel/) to collect our dataset.

Best,
Jingxuan

**Comment by ivg** [comment]
BAP currently supports more or less all ARM architectures before ARM7 (including). The thumb mode is not fully supported (though in BAP 2.0 it finally becomes possible), neither ARMv8 is supported.

**Comment by francozappa** [comment]
Ok!

Thanks for the quick answer.
