### ISSUE TITLE
Some issues about evaluation

### ISSUE THREAD

**Issue by mingfure** [eth-sri/debin#13]
Hi, Jingxuan
I want to see the evaluation result of binnary `lcrack`, but there were two problems.
First, I use your given model to predict `example/stripped/lcrack` to get `lcrack` with debug info.
```
$ python3 py/predict.py  --binary examples/stripped/lcrack  --output ./lcrack \
           --elf_modifier cpp/modify_elf.so 	  -two_pass \
           --fp_model models/variable/x86/  --n2p_url http://localhost:8604
```
And I also download the lcrack.x86 predict result called `output.binary` from debin.ai. **Why are they so different in size?**
```
$ ll
-rw-rw-r--  1 root **43K** Oct 15 21:11 lcrack
-rwxr-xr-x  1 root **96K** Oct 15 21:09 output.binary
...
```
Second, The accuracy of the first stage was normal for either `lcrack`(predict by models) or `output.binary`(from debin.ai), but the precision of both of them in the second stage  were **less than 10%.  **What could possibly cause this?
```
lcrack:
precision_1p: 0.6963103122043519
recall_1p: 0.7880085653104925
f1_1p: 0.7393269713711702
accuracy_1p: 0.8629883843717001

precision_2p: 0.04434589800443459
recall_2p: 0.0499001996007984
f1_2p: 0.046959380136182206

precision_name_2p: 0.021314387211367674
recall_name_2p: 0.023928215353938187
f1_name_2p: 0.022545796148426493

precision_ttype_2p: 0.06731620903454384
recall_ttype_2p: 0.07592407592407592
f1_ttype_2p: 0.07136150234741784

output.binary:
precision_1p: 0.6783004552352049
recall_1p: 0.7627986348122867
f1_1p: 0.7180722891566266
accuracy_1p: 0.8375751966682091

precision_2p: 0.05355932203389831
recall_2p: 0.06030534351145038
f1_2p: 0.05673249551166966

precision_name_2p: 0.020380434782608696
recall_name_2p: 0.02262443438914027
f1_name_2p: 0.021443888491779844

precision_ttype_2p: 0.08660351826792964
recall_ttype_2p: 0.09891808346213292
f1_ttype_2p: 0.09235209235209237
```

[lcrack.txt](https://github.com/eth-sri/debin/files/3729564/lcrack.txt)
[output .binary.txt](https://github.com/eth-sri/debin/files/3729566/output.binary.txt)

**Comment by LostBenjamin** [comment]
Hi,

First, `output.binary` has predicted debug information. Usually debug information is very space-consuming.

Second, what were the command and models you use for getting the accuracy? Also, how did you manage to get accuracy for `output.binary` from `debin.ai`?

Best,
Jingxuan

**Comment by mingfure** [comment]
Hi,
First, the size of stripped lcrack in `example/stripped` is 40k, `lcrack(43k)` is generate by `predict.py  --output` option which should also has predicted debug information. So, in my understanding, it should be as same as `output.binary(96k)` from debin.ai corresponding to `lcrack.x86`.
Second, the models is [debin_models.tar.gz](https://files.sri.inf.ethz.ch/debin_models.tar.gz). 
The command is
```
$ python3 py/evaluate.py \
          --binary output.binary \ # download from debin.ai
          --debug_info examples/debug/lcrack \
          -two_pass \
          --fp_model models/variable/x86/ \
          --n2p_url http://localhost:8604 \
          --stat ./output_binary.txt
```
Please point out whether there is any mistake in my operation. Thank you~
Mingfure

**Comment by LostBenjamin** [comment]
Hi,

First, this is a bug in the released version. Thank you for pointing it out! We fixed it in this repo and [debin.ai](debin.ai). Now they give similarly sized (~60K) outputs for `lcrack`. For evaluation purposes, please use the repo.

Second, this is a wrong usage of `py/evaluate.py`. Its purpose is not to compare an output binary with ground truth. Instead, the option `--binary` should be a stripped binary. Then, it will call inference on the stripped binary and do evaluation. Please look at our example command for correct usage.

Best,
Jingxuan

**Comment by mingfure** [comment]
Hi,
First, you're welcome. But unfortunatly they're still different sizes.
Output from [debin.ai](debin.ai) for `lcrack` : ~60K
Output from the following command for `lcrack`(lcrack.output): 46K. 
Shouldn't they be the same?
```
python3 py/predict.py \
          --binary examples/stripped/lcrack \
          --output ./lcrack.output \
          --elf_modifier cpp/modify_elf.so \
          -two_pass \
          --fp_model models/variable/x86/ \
          --n2p_url http://localhost:8604
```

Second, thank you for pointing my wrong usage out!

**Comment by LostBenjamin** [comment]
Hi,

I just tried the docker with newest version of the code. `lcrack.output` is ~60K. Are you sure you are using the newest version?

Best,
Jingxuan

**Comment by mingfure** [comment]
From the results, it seems to have little effect. Thank you for your reply!
