### ISSUE TITLE
Parse the binary which is statically compiled.

### ISSUE THREAD

**Issue by rickchen147258** [eth-sri/debin#14]
Hello,
After reading your paper, I am very interested in your work and want to try it.
So I wrote an easy C program like this
![image](https://user-images.githubusercontent.com/29858582/79632610-03abfc80-8193-11ea-80f7-aa4b855115d9.png)
Then I used the gcc with -static to compile it.
After compiling, I used the built-in strip to strip the binary code and put the binary code to your website.
But I get the error like this
![image](https://user-images.githubusercontent.com/29858582/79632664-67cec080-8193-11ea-9255-2d382a68764a.png)
Is it the problem for me to compile in the wrong way or is the system bug?
By the way, The website can parse binary normally if I don't compile in statically.
Thank you.

**Comment by LostBenjamin** [comment]
Hi,

Sorry for the late replay. Can you send me the compiled binary so that I can check?

Best,
Jingxuan
