### ISSUE TITLE
 Can Debin be used in MIPS or PPC?

### ISSUE THREAD

**Issue by yasong** [eth-sri/debin#15]
Thank you for opening the source code. In the paper, we know that debin supports x86, x64 and ARM. I want to know if it can be used in MIPS or PPC. Are there some reasons that this paper didn't mention MIPS or PPC, for example, the BAP didn't support MIPS and PPC when you did your work in debin? Thank you.

**Comment by LostBenjamin** [comment]
Hi,

Due to limited time and resource, we opted to support the most popular architectures. Since BAP supports MIPS, adding support for MIPS should be straightforward.

Best,
Jingxuan
