### ISSUE TITLE
Errors while generating symbols

### ISSUE THREAD

**Issue by Ruturaj4** [eth-sri/debin#16]
I have built and installed all the dependencies as explained. But when I try to execute the command:

`python3.6 py/predict.py --binary /mnt/d/Ruturaj/binary_research/pin/my_tool/a.out --output ./test1.output --elf_modifier cpp/modify_elf.so -two_pass --fp_model models/variable/x86/ --n2p_url http://localhost:8604`

It gives me following errors:

```
bap: unknown option `--symbolizer'.
Usage: bap disassemble [OPTION]... [FILE]
Try `bap disassemble --help' or `bap --help' for more information.
Traceback (most recent call last):
  File "py/predict.py", line 87, in <module>
    main()
  File "py/predict.py", line 73, in main
    b = Binary(config, elffile)
  File "/mnt/d/Ruturaj/binary_research/debin/debin/py/binary.py", line 90, in __init__
    bap_json = json.loads(bap_result)
  File "/usr/lib/python3.6/json/__init__.py", line 354, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.6/json/decoder.py", line 339, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.6/json/decoder.py", line 357, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
```

Is this because of bap's version difference? or is this because I missed something during the build?

**Comment by LostBenjamin** [comment]
Hi,

The error message shows that bap did not recognize some command line option. So it may be because of bap's version difference. What is your bap version?

Best,
Jingxuan

**Comment by Ruturaj4** [comment]
yes, I figured it out. Thanks for the comment. I was using the latest bap version.
