### ISSUE TITLE
Dockerfile downloading Python version 3.5

### ISSUE THREAD

**Issue by valgh** [eth-sri/debin#17]
The dockerfile running on Ubuntu 16.04 downloads by default Python version 3.5, but version >3.6 is required by scipy:

>  => ERROR [27/35] RUN pip3 install -r requirements.txt                                                                                                                                                                                 24.3s
> ------
>  > [27/35] RUN pip3 install -r requirements.txt:
> #31 2.377 Collecting numpy==1.14.2 (from -r requirements.txt (line 1))
> #31 4.009   Downloading https://files.pythonhosted.org/packages/ea/31/991207e6234b46a1228be970735ead9d6f06a298917d6f718c5e32e835bb/numpy-1.14.2-cp35-cp35m-manylinux1_x86_64.whl (12.1MB)
> #31 8.317 Collecting scipy (from -r requirements.txt (line 2))
> #31 9.026   Downloading https://files.pythonhosted.org/packages/53/10/776750d57ade26522478a92a2e14035868624a6a62f4157b0cc5abd4a980/scipy-1.5.2.tar.gz (25.4MB)
> #31 23.41     Complete output from command python setup.py egg_info:
> #31 23.41     Traceback (most recent call last):
> #31 23.41       File "<string>", line 1, in <module>
**> #31 23.41       File "/tmp/pip-build-fk2ac076/scipy/setup.py", line 31, in <module>
> #31 23.41         raise RuntimeError("Python version >= 3.6 required.")
> #31 23.41     RuntimeError: Python version >= 3.6 required.**
> #31 23.41
> #31 23.41     ----------------------------------------
> ------

Updating Ubuntu's repositories and forcing version 3.6 on the dockerfile solved the problem.

**Comment by LostBenjamin** [comment]
Hi,

Could you please create a pull request for this? Thank you!

Best,
Jingxuan

**Comment by valgh** [comment]
Hello, 

sure I will as soon as possible (sorry I just saw this message).
