### ISSUE TITLE
Report some error when i build docker images

### ISSUE THREAD

**Issue by hhqd** [eth-sri/debin#19]
hello

When i run `sudo docker build -t debin .`  report error.

My os ls ubuntu16.04.

Thanks!!!

`Step 10/31 : RUN cd Nice2Predict &&     bazel build //... &&     cd ..
 ---> Running in 633b421a0ead
Extracting Bazel installation...

Starting local Bazel server and connecting to it...
Loading: 
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Loading: 0 packages loaded
Analyzing: 24 targets (15 packages loaded, 0 targets configured)
Analyzing: 24 targets (24 packages loaded, 211 targets configured)
Analyzing: 24 targets (24 packages loaded, 211 targets configured)
Analyzing: 24 targets (24 packages loaded, 211 targets configured)
Analyzing: 24 targets (24 packages loaded, 211 targets configured)
ERROR: /debin/Nice2Predict/util/zstream/BUILD:13:1: no such package '@com_google_googletest//': Error downloading [https://github.com/google/googletest/archive/7c6353d29a147cad1c904bf2957fd4ca2befe135.zip] to /root/.cache/bazel/_bazel_root/c6b3ba3d23771fdadfb5e0d5e04db5e8/external/com_google_googletest/7c6353d29a147cad1c904bf2957fd4ca2befe135.zip: Tried to reconnect at offset 49,231 but server didn't support it and referenced by '//util/zstream:zstream_test'
ERROR: Analysis of target '//util/zstream:zstream_test' failed; build aborted: no such package '@com_google_googletest//': Error downloading [https://github.com/google/googletest/archive/7c6353d29a147cad1c904bf2957fd4ca2befe135.zip] to /root/.cache/bazel/_bazel_root/c6b3ba3d23771fdadfb5e0d5e04db5e8/external/com_google_googletest/7c6353d29a147cad1c904bf2957fd4ca2befe135.zip: Tried to reconnect at offset 49,231 but server didn't support it
INFO: Elapsed time: 116.008s
INFO: 0 processes.
FAILED: Build did NOT complete successfully (24 packages loaded, 211 targets configured)
FAILED: Build did NOT complete successfully (24 packages loaded, 211 targets configured)
`

**Comment by LostBenjamin** [comment]
Hi,

I just successfully built the docker image. Can you please try again?

Best,
Jingxuan
