### ISSUE TITLE
Debin's training scripts abnormally terminated

### ISSUE THREAD

**Issue by xinjin95** [eth-sri/debin#22]
Hi Debin developers,

I tried to train Debin with 2K x64 binaries but it abnormally terminated without any log messages indicating the reasons.

With `ps` command, I find the training process `python py/train_variable.py` is with the `S+` status, which means it's in the "interruptible sleep" state.

How can I find the root cause?

**Comment by LostBenjamin** [comment]
Hi,

It is also hard for me to find the root cause. Can you provide more information?

One possible reason is out-of-memory error if you run the scripts with too much training data.

Best,
Jingxuan
