### ISSUE TITLE
train_variable.py  does anything?

### ISSUE THREAD

**Issue by urialon** [eth-sri/debin#4]
Hi again,
I ran, according to the README, the following command:
```
python3 py/train_variable.py --bin_list my_dataset/train/list.txt --bin_dir my_dataset/train/stripped/ --debug_dir my_dataset/train/debug/ --out_model new_models/variable/x86/ --reg_num_f 100 --off_num_f 100 --workers 64
```

It finished after 3 hours (in which I saw high cpu activity of `python3` and `bap`), but it didn't seem to do anything: I don't see any file in new_models/variable/x86/ , and it didn't produce any error.

Do you have an idea what am I missing?
Thanks!

**Comment by LostBenjamin** [comment]
I don't see any problem (if you follow the example to put "stripped" binaries in `my_dataset/train/stripped/` and corresponding debug symbols in `my_dataset/train/debug/`, and all the binary names in `my_dataset/train/list.txt`).

I would suggest you to try one or several samples first (or you can give me to try), make sure it works in the right way and then extend to full dataset.

ps:
it seems that your dataset is quite large as you set 64 workers. So you may want to adjust the parameter `--reg_num_f` and `--off_num_f`, which controls the feature dimension for registers and offsets, respectively. 100 is very small and only for our example.

**Comment by urialon** [comment]
Thanks.
What are the values of reg_num_f and off_num_f in your final large model?

**Comment by LostBenjamin** [comment]
I used 10000

**Comment by urialon** [comment]
Thanks!!
