### ISSUE TITLE
Nice2Predict Runtime error

### ISSUE THREAD

**Issue by urialon** [eth-sri/debin#5]
Hi,
`train_crf` had finished extracting features and wrote them to `features.json`, but now Nice2Predict is throwing an error. I tried to reproduce the error by running exactly the same command line from the script and it does reproduce.
I'm running on Ubuntu 16 on a machine with 64 cores 800 GB RAM, using your docker container.
Here is the command I am running and the error, looks like a reentrancy issue while reading the features json:

```
root@5d09f1c9ecd5:/debin# ./Nice2Predict/bazel-bin/n2p/training/train_json --input new_models/crf/feature.json --valid_labels c_valid_labels --out_model new_models/crf/x86/model --num_threads 64 --training_method pl --max_labels_z 8
terminate called after throwing an instance of 'Json::RuntimeError'
  what():  Exceeded stackLimit in readValue().
*** Aborted at 1549258687 (unix time) try "date -d @1549258687" if you are using GNU date ***
terminate called recursively
PC: @     0x7f235be69428 gsignal
terminate called recursively
*** SIGABRT (@0xb94e) received by PID 47438 (TID 0x7f2300ff9700) from PID 47438; stack trace: ***
    @     0x7f235ccdf390 (unknown)
terminate called recursively
    @     0x7f235be69428 gsignal
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
terminate called recursively
    @     0x7f235be6b02a abort
    @     0x7f235c4a384d __gnu_cxx::__verbose_terminate_handler()
    @     0x7f235c4a16b6 (unknown)
    @     0x7f235c4a1701 std::terminate()
    @     0x7f235c4ccd38 (unknown)
    @     0x7f235ccd56ba start_thread
    @     0x7f235bf3b41d clone
    @                0x0 (unknown)
Aborted (core dumped)
```

It happens even if I take only the first 10 lines of `features.json` (which are also large 106MB).

Thanks! 
Uri

**Comment by vraychev** [comment]
Most likely this is a bug in JSONcpp, but appears with newer versions.
https://github.com/open-source-parsers/jsoncpp/issues/361

**Comment by urialon** [comment]
Hi Veselin,
Yes, we talked about this bug ~2-3 years ago, and I remember the patch that you suggested them (making the static counter `thread_local`),
but I remembered that it appeared only with older versions of Ubuntu. I.e., I thought that in Ubuntu 16 this wasn't a problem.

**Comment by LostBenjamin** [comment]
For now, could you edit the code of JSONcpp parser in N2P and recompile N2P according to [this link](https://github.com/eth-sri/Nice2Predict/pull/24/files)? This removes the check for stack limit. Or you can try increasing the value of `stackLimit_g` variable to increase stack limit.

**Comment by urialon** [comment]
Thanks! N2P training now runs for a few minutes already.
