### ISSUE TITLE
Debug Symbol Package for Dataset

### ISSUE THREAD

**Issue by mingfure** [eth-sri/debin#9]
Hello~ When  I try to get "not stripped binaries" following the steps on [Debug Symbol Package](https://wiki.ubuntu.com/Debug%20Symbol%20Packages), the -dbgsym packages would be installed successfully, but the binaries still is stripped. This confuse me a lot. I tried lcrack/coretils/hello/acpid, only lcrack can be work(generate not stripped version). So, could you tell me how to generate "not stripped" binaries?

**Comment by LostBenjamin** [comment]
Hi,

After you install packages ending with `-dbgsym`, the debug symbol of installed binaries should be stored at sub-directories of `/usr/lib/debug`. I just tried and confirmed this on Ubuntu 16.04.

Let me know whether this works for you.

Best,
Jingxuan

**Comment by mingfure** [comment]
As you said，when I install lcrack and lcrack-dbgsym by `sudo apt-get install lcrack lcrack-dbgsym`. the non-stripped version of lcrack can be found at `/usr/lib/debug/usr/bin/`.
```
 /usr/lib/debug > ll usr/bin
total 196K
-rwxr-xr-x 1 root root  94K Jan  4  2010 lcrack  // non-stripped version
-rwxr-xr-x 1 root root  49K Jan  4  2010 lcrack_mktbl
-rwxr-xr-x 1 root root 9.4K Jan  4  2010 lcrack_mkword
-rwxr-xr-x 1 root root  33K Jan  4  2010 lcrack_regex
``` 
So I install coreutils, dpkg(choose these ones because they are mentioned in your paper) and hello packages ending with `-dbgsym` in the same way. But during this time, the number of files at the directories of `/usr/lib/debug` is 320 and has no changes.
```
/usr/lib/debug > ls -lR |wc -l    
320 // most of them are .so libs at directory of x86_64-linux-gnu 
```
Why? Is it because they are stored elsewhere? I try this on Ubuntu 16.04.6 LTS.
Best wishes,
Ming

**Comment by LostBenjamin** [comment]
Hi,

Debug symbols can be stored at the hidden directory `/usr/lib/debug/.build-id` indexed by build ids of the binaries.

To check build id of a binary (e.g., `/usr/bin/hello`), you can use the command `readelf -x .note.gnu.build-id /usr/bin/hello`. Then you can find its debug symbol under `/usr/lib/debug/.build-id` according to its build id.

If you run `ls -lRa /usr/lib/debug | wc -l`, you shall see a difference before and after installing a package ending with `-dbgsym`.

Let me know whether this works for you. Thanks!

Best,
Jingxuan

**Comment by mingfure** [comment]
Hi~
I'm so excited to find that your solution perfectly solved the problem I met! 
Thank you so much for your help!!!
Best wishes,
Ming
